## NumPy Array operations

In [2]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing", arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing ",arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing  7


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific eLement", arr_2d[1,2]) ## first row ka second element

print("Entire row :",arr_2d[1])
print("Entire column :",arr_2d[:,1])

Specific eLement 6
Entire row : [4 5 6]
Entire column : [2 5 8]


## Sorting

In [ ]:
unsorted_arr = np.array([1,2,3,10,2,4,35,2,4])
print("Sorted Array ", np.sort(unsorted_arr))


unsorted_arr_2d = np.array([[3, 2],
                           [1, 0],
                           [2, 1]])

print("Sorted 2D array by column", np.sort(unsorted_arr_2d,axis=0))



Sorted Array  [ 1  2  2  2  3  4  4 10 35]
Sorted 2D array by column [[2 3]
 [0 1]
 [1 2]]


## Filter


In [16]:
numbers  = np.array([1,2,3,4,5,6,7,7,8,9,9])

even_number = numbers[numbers % 2 == 0]

print("Even numbers ", even_number)

Even numbers  [2 4 6 8]


## Filter with mask

In [17]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [6 7 7 8 9 9]


## Fancy indexing and np.where()

In [ ]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
## where_result will store the indices of the numbers greater than 5
print("NP Where", numbers[where_result])

[1 3 5]
NP Where [6 7 7 8 9 9]


In [ ]:
condition_array = np.where(numbers > 10, "true", "false")
print(condition_array)

[1 2 3 4 5 6 7 7 8 9 9]


## Adding and  removing data


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shapes ",a.shape == b.shape)

Compatibility Shapes  True


In [ ]:
orignal = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((orignal,new_row))

print("Orignal:\n",orignal)

print("\n With new Row :\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((orignal,new_col))

print("\n With new column :\n",with_new_col)

Orignal:
 [[1 2]
 [3 4]]

 With new Row :
 [[1 2]
 [3 4]
 [5 6]]

 With new column :
 [[1 2 7 6]
 [3 4 8 9]]


## Delete in array

In [9]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr,2)

print("\n Array after deletion:",deleted)


 Array after deletion: [1 2 4 5]
