In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Data structure: [restaurant id, 2021, 2022, 2023, 2024]

sales_data = np.array([

[1, 150000, 180000, 220000, 25000],# Paradise Biryani    

[2, 120000, 140000, 160000, 190000],# Beijing Bites

[3, 200000, 230000, 260000, 300000], # Pizza Hub

[4, 180000, 210000, 240000, 270000],# Burger Point

[5, 160000, 185000, 205000, 230000]# Chai Point
)]


print("")

In [ ]:
# Data structure: [restaurant id, 2021, 2022, 2023, 2024]

sales_data = np.array([

[1, 150000, 180000, 220000, 25000],# Paradise Biryani    

[2, 120000, 140000, 160000, 190000],# Beijing Bites

[3, 200000, 230000, 260000, 300000], # Pizza Hub

[4, 180000, 210000, 240000, 270000],# Burger Point

[5, 160000, 185000, 205000, 230000]# Chai Point
])


print("=== Zomato sales analysis ===")
print("\n Sales data shape",sales_data.shape)
print("\n Sample data for 1st 3 restaurants\n", sales_data[:3])


=== Zomato sales analysis ===

 Sales data shape (5, 5)

 Sample data for 1st 3 restaurants
 [[     1 150000 180000 220000  25000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
#total sales per year

print(np.sum(sales_data,axis=0))

#yearly total

print(np.sum(sales_data[:,1:]))


[     15  810000  945000 1085000 1015000]
